1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import pandas as pd
import numpy as np

In [29]:
a= np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [24]:
a1= np.arange(10,50)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
arr= np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [23]:
arr1 = np.array([1,2,0,0,4,0])
print(arr1)
for i in range(6):
    if arr1[i]!=0:
        print("Index",i)

[1 2 0 0 4 0]
Index 0
Index 1
Index 4


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [14]:
arr2= np.random.randint(10,51,size=(10,10))
print(arr2)
print("Minimum Value : ",np.min(arr2))
print("Maximum Value : ",np.max(arr2))

[[17 25 26 36 26 28 46 18 20 31]
 [44 16 38 32 40 23 31 34 35 45]
 [14 14 50 37 30 11 14 10 14 39]
 [18 43 23 36 37 12 44 43 26 25]
 [27 11 27 11 19 42 31 11 18 37]
 [33 29 19 46 24 12 34 15 17 31]
 [28 42 16 32 45 46 22 16 45 26]
 [29 20 42 28 12 42 48 14 13 16]
 [21 16 19 35 38 28 29 24 10 19]
 [20 13 42 46 30 46 15 43 14 49]]
Minimum Value :  10
Maximum Value :  50


6. Create a random vector of size 30 and find the mean value.

In [36]:
arr3= np.random.randint(0,100,30)
print(arr3)
print("Mean of Vector is : ",np.mean(arr3))

[39  8 27 33 29 62 99 97 69 30 83 19  3 29 51 72 68  5 60 87 60 46 19 67
 45 66 48 36 98 22]
Mean of Vector is :  49.233333333333334
